## REMEMBER TO SET UP YOUR GITHUB REPO FOR TRAVIS
## Go to: https://travis-ci.org/VirtualFlyBrain for details
sudo: required

services:
  - docker

before_install:
  - docker pull obolibrary/osklite

# command to run tests
script: cd src/ontology && sh test.sh

#after_success:
#  coveralls

# whitelist
branches:
  only:
    - master
    - test-travis

### Add your own lists here
### See https://github.com/INCATools/ontology-starter-kit/issues/35
notifications:
  email:
    - obo-ci-reports-all@groups.io
